# Generated by Django 4.2.11 on 2026-05-17 09:39

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Property company name", max_length=200),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                (
                    "onboarded_by",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of the user who created this tenant",
                        null=True,
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Plan"),
                            ("premium", "Premium Plan"),
                            ("enterprise", "Enterprise Plan"),
                        ],
                        default="basic",
                        max_length=50,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=dict,
                        help_text="Available features for this property company",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "expected_pan",
                    models.CharField(
                        blank=True,
                        help_text="PAN required for verification",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "expected_gst",
                    models.CharField(
                        blank=True,
                        help_text="GST required for verification",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Property Company",
                "verbose_name_plural": "Property Companies",
            },
        ),
        migrations.CreateModel(
            name="KYC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "id_proof",
                    models.FileField(blank=True, null=True, upload_to="kyc_docs/id/"),
                ),
                (
                    "pan_card",
                    models.FileField(blank=True, null=True, upload_to="kyc_docs/pan/"),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("business_address", models.TextField(blank=True, null=True)),
                (
                    "business_reg",
                    models.FileField(
                        blank=True, null=True, upload_to="kyc_docs/business/"
                    ),
                ),
                ("gst_number", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "gst_cert",
                    models.FileField(blank=True, null=True, upload_to="kyc_docs/gst/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("resubmission_required", "Resubmission Required"),
                        ],
                        default="not_started",
                        max_length=30,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to="tenants.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Features"),
                            ("premium", "Premium Features"),
                            ("enterprise", "Enterprise Features"),
                        ],
                        default="basic",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_trial", models.BooleanField(default=False)),
                ("trial_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "monthly_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("max_users", models.IntegerField(default=100)),
                ("max_properties", models.IntegerField(default=10)),
                ("max_units", models.IntegerField(default=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="tenants.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_color", models.CharField(default="#14213D", max_length=7)),
                ("secondary_color", models.CharField(default="#C1CFEB", max_length=7)),
                ("accent_color", models.CharField(default="#EAB308", max_length=7)),
                ("logo_url", models.URLField(blank=True, max_length=500, null=True)),
                ("favicon_url", models.URLField(blank=True, max_length=500, null=True)),
                ("login_message", models.TextField(blank=True, default="")),
                ("login_page_message", models.TextField(blank=True, default="")),
                ("footer_text", models.TextField(blank=True, default="")),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("date_format", models.CharField(default="MM/DD/YYYY", max_length=20)),
                ("fiscal_year_start", models.CharField(default="01", max_length=2)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("push_notifications", models.BooleanField(default=True)),
                ("payment_reminders", models.BooleanField(default=True)),
                ("payment_reminder_days", models.IntegerField(default=3)),
                ("maintenance_updates", models.BooleanField(default=True)),
                ("lease_expiry_alerts", models.BooleanField(default=True)),
                ("lease_expiry_days", models.IntegerField(default=30)),
                ("security_alerts", models.BooleanField(default=True)),
                ("weekly_digest", models.BooleanField(default=False)),
                ("monthly_report", models.BooleanField(default=True)),
                ("new_resident_welcome", models.BooleanField(default=True)),
                ("document_expiry_alerts", models.BooleanField(default=True)),
                ("otp_required", models.BooleanField(default=True)),
                ("otp_expire_minutes", models.IntegerField(default=5)),
                ("payment_due_days", models.IntegerField(default=5)),
                ("late_fee_enabled", models.BooleanField(default=False)),
                (
                    "late_fee_type",
                    models.CharField(default="percentage", max_length=20),
                ),
                (
                    "late_fee_percentage",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "late_fee_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("grace_period_days", models.IntegerField(default=5)),
                ("auto_invoicing", models.BooleanField(default=False)),
                ("invoice_day_of_month", models.IntegerField(default=1)),
                ("razorpay_enabled", models.BooleanField(default=False)),
                (
                    "razorpay_key_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "razorpay_webhook_secret",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("paypal_enabled", models.BooleanField(default=False)),
                (
                    "paypal_client_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("bank_transfer_enabled", models.BooleanField(default=True)),
                ("bank_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "bank_account_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "bank_account_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "bank_routing_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("quickbooks_enabled", models.BooleanField(default=False)),
                ("google_calendar_enabled", models.BooleanField(default=False)),
                ("slack_enabled", models.BooleanField(default=False)),
                (
                    "slack_webhook_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("api_enabled", models.BooleanField(default=False)),
                ("api_key", models.CharField(blank=True, default="", max_length=100)),
                ("webhook_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "webhook_secret",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("auto_assign_maintenance", models.BooleanField(default=False)),
                (
                    "maintenance_categories",
                    models.JSONField(
                        default=list, help_text="Available maintenance categories"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenants.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlatformPaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("stripe_card", "Card (Stripe)"),
                            ("bank_account", "Bank Account"),
                        ],
                        max_length=50,
                    ),
                ),
                ("gateway_customer_id", models.CharField(blank=True, max_length=200)),
                ("gateway_payment_method_id", models.CharField(max_length=200)),
                ("card_last4", models.CharField(blank=True, max_length=4)),
                ("card_brand", models.CharField(blank=True, max_length=50)),
                ("card_exp_month", models.IntegerField(blank=True, null=True)),
                ("card_exp_year", models.IntegerField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="tenants.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("plan_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("verified", "Verified"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("billing_email", models.EmailField(max_length=254)),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("remarks", models.TextField(blank=True)),
                (
                    "pending_features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Features to activate upon payment",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_invoices",
                        to="tenants.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlatformAutopayEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("frequency", models.CharField(default="monthly", max_length=20)),
                ("next_payment_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenants.platformpaymentmethod",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autopay_enrollment",
                        to="tenants.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KYCLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kyc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="tenants.kyc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.client",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["is_active"], name="tenants_cli_is_acti_9a4d57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["created_on"], name="tenants_cli_created_47c967_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["subscription_plan"], name="tenants_cli_subscri_8885cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="domain",
            unique_together={("tenant", "is_primary")},
        ),
    ]
