# Generated by Django 4.2.11 on 2026-05-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantsettings",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
    ]
