# Generated by Django 4.2.11 on 2026-05-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_alter_tenantsettings_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantfeature",
            name="category",
            field=models.CharField(
                choices=[
                    ("primary", "Primary Modules"),
                    ("secondary", "Secondary Services"),
                    ("advanced", "Advanced Tools"),
                    ("setup", "Onboarding & Setup"),
                    ("basic", "Basic Features"),
                    ("premium", "Premium Features"),
                    ("enterprise", "Enterprise Features"),
                    ("core", "Core Features"),
                ],
                default="primary",
                max_length=50,
            ),
        ),
    ]
