# Generated by Django 5.0.4 on 2026-06-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenantsettings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
