# Generated by Django 5.0.4 on 2026-06-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ein',
            field=models.CharField(blank=True, help_text='Employer Identification Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sos_id',
            field=models.CharField(blank=True, help_text='State Registration Number (SOS ID)', max_length=50, null=True),
        ),
    ]
