# Generated by Django 4.2.11 on 2026-06-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_alter_tenantfeature_category"),
        ("tenants", "0005_client_ein_client_sos_id"),
    ]

    operations = []
