# Generated by Django 4.2.11 on 2026-06-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_merge_20260615_2359"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="pincode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="management_fee_type",
            field=models.CharField(
                choices=[("percentage", "Percentage"), ("fixed", "Fixed Amount")],
                default="percentage",
                help_text="Global default management cut taken from rent.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="management_fee_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Global management fee percentage or fixed amount",
                max_digits=10,
            ),
        ),
    ]
