# Generated by Django 4.2.11 on 2026-05-17 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Geico, State Farm, Progressive", max_length=200
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("property", "Property Insurance"),
                            ("liability", "Liability Insurance"),
                            ("flood", "Flood Insurance"),
                            ("earthquake", "Earthquake Insurance"),
                            ("other", "Other"),
                        ],
                        default="property",
                        max_length=50,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("policy_number", models.CharField(blank=True, max_length=100)),
                (
                    "coverage_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "premium_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("policy_start_date", models.DateField(blank=True, null=True)),
                ("policy_end_date", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Insurance Provider",
                "verbose_name_plural": "Insurance Providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UtilityProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "utility_category",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("water", "Water"),
                            ("gas", "Gas"),
                            ("internet", "Internet"),
                            ("insurance", "Insurance"),
                            ("property_tax", "Property Tax"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("account_number", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UtilityType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("water", "Water"),
                            ("gas", "Gas"),
                            ("internet", "Internet"),
                            ("maintenance", "Maintenance"),
                            ("parking", "Parking"),
                            ("security", "Security"),
                            ("waste_management", "Waste Management"),
                            ("property_tax", "Property Tax"),
                            ("insurance", "Insurance"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "unit_of_measurement",
                    models.CharField(
                        help_text="e.g., kWh, gallons, cubic meters", max_length=50
                    ),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Rate per unit", max_digits=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Utility Types",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="BuildingInsurance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("policy_number", models.CharField(max_length=100)),
                (
                    "coverage_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "premium_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("policy_start_date", models.DateField()),
                ("policy_end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurances",
                        to="properties.building",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_insurances",
                        to="utilities.insuranceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Building Insurance",
                "verbose_name_plural": "Building Insurances",
                "ordering": ["-policy_start_date"],
            },
        ),
        migrations.CreateModel(
            name="UtilityMeterReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reading_date", models.DateField()),
                ("reading_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reading_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("automatic", "Automatic"),
                            ("estimated", "Estimated"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("meter_number", models.CharField(blank=True, max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="meter_readings/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_readings",
                        to="properties.unit",
                    ),
                ),
                (
                    "utility_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="utilities.utilitytype",
                    ),
                ),
            ],
            options={
                "ordering": ["-reading_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["unit", "reading_date"],
                        name="utilities_u_unit_id_68676a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UtilityBill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bill_number", models.CharField(max_length=50, unique=True)),
                ("billing_period_start", models.DateField()),
                ("billing_period_end", models.DateField()),
                (
                    "previous_reading",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "current_reading",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("consumption", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rate_per_unit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "additional_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_bills",
                        to="properties.unit",
                    ),
                ),
                (
                    "utility_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="utilities.utilitytype",
                    ),
                ),
            ],
            options={
                "ordering": ["-billing_period_start", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["unit", "billing_period_start"],
                        name="utilities_u_unit_id_9dd8ed_idx",
                    ),
                    models.Index(
                        fields=["status", "due_date"],
                        name="utilities_u_status_52af69_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "utility_type",
                        "unit",
                        "billing_period_start",
                        "billing_period_end",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="BuildingUtilityConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("connection_number", models.CharField(max_length=100)),
                ("connection_date", models.DateField()),
                ("meter_number", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_connections",
                        to="properties.building",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_connections",
                        to="utilities.utilityprovider",
                    ),
                ),
                (
                    "utility_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_connections",
                        to="utilities.utilitytype",
                    ),
                ),
            ],
            options={
                "ordering": ["building", "utility_type"],
                "unique_together": {("building", "provider", "connection_number")},
            },
        ),
    ]
