# Generated by Django 4.2.11 on 2026-06-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0002_alter_utilitybill_generated_by_and_more"),
        ("utilities", "0002_utilitybill_invoiced"),
    ]

    operations = []
