# Generated by Django 4.2.11 on 2026-05-17 09:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "amenity_type",
                    models.CharField(
                        choices=[
                            ("gym", "Gym/Fitness Center"),
                            ("pool", "Swimming Pool"),
                            ("clubhouse", "Clubhouse"),
                            ("playground", "Playground"),
                            ("sports_court", "Sports Court"),
                            ("garden", "Garden/Park"),
                            ("theater", "Theater/Auditorium"),
                            ("conference_room", "Conference Room"),
                            ("game_room", "Game Room"),
                            ("library", "Library"),
                            ("spa", "Spa/Sauna"),
                            ("rooftop", "Rooftop Terrace"),
                            ("bbq_area", "BBQ Area"),
                            ("party_hall", "Party Hall"),
                            ("coworking", "Co-working Space"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("building", models.CharField(blank=True, max_length=200)),
                ("floor", models.CharField(blank=True, max_length=50)),
                ("location_details", models.TextField(blank=True)),
                (
                    "capacity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "area_sqft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("maintenance", "Under Maintenance"),
                            ("closed", "Closed"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_bookable", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("operating_hours", models.JSONField(blank=True, default=dict)),
                ("is_24_hours", models.BooleanField(default=False)),
                ("closed_days", models.JSONField(blank=True, default=list)),
                (
                    "max_booking_duration_hours",
                    models.IntegerField(
                        default=2,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "min_advance_booking_hours",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_advance_booking_days",
                    models.IntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "bookings_per_user_per_day",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "bookings_per_user_per_month",
                    models.IntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "price_per_hour",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "cancellation_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("equipment_available", models.JSONField(blank=True, default=list)),
                ("images", models.JSONField(blank=True, default=list)),
                ("video_url", models.CharField(blank=True, max_length=500)),
                ("rules", models.TextField(blank=True)),
                ("guidelines", models.TextField(blank=True)),
                ("manager_name", models.CharField(blank=True, max_length=200)),
                ("manager_phone", models.CharField(blank=True, max_length=20)),
                ("manager_email", models.EmailField(blank=True, max_length=254)),
                ("total_bookings", models.IntegerField(default=0)),
                ("active_bookings", models.IntegerField(default=0)),
                (
                    "rating_average",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("next_maintenance", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amenities_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AmenityBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_number", models.CharField(max_length=50, unique=True)),
                ("booking_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("duration_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "number_of_people",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("guest_names", models.JSONField(blank=True, default=list)),
                ("purpose", models.TextField()),
                ("special_requirements", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "booking_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=200)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "refund_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="amenities.amenity",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amenity_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity Booking",
                "verbose_name_plural": "Amenity Bookings",
                "ordering": ["-booking_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="AmenityRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("priority", models.IntegerField(default=0)),
                ("is_mandatory", models.BooleanField(default=False)),
                ("show_at_booking", models.BooleanField(default=True)),
                ("requires_acknowledgment", models.BooleanField(default=False)),
                (
                    "violation_penalty",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("penalty_description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_rules",
                        to="amenities.amenity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity Rule",
                "verbose_name_plural": "Amenity Rules",
                "ordering": ["-priority", "title"],
            },
        ),
        migrations.CreateModel(
            name="AmenityClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "class_type",
                    models.CharField(
                        choices=[
                            ("yoga", "Yoga"),
                            ("zumba", "Zumba"),
                            ("dance", "Dance"),
                            ("fitness", "Fitness/Aerobics"),
                            ("swimming", "Swimming Lessons"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("instructor_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("days_of_week", models.JSONField(default=list)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("max_participants", models.IntegerField(default=20)),
                ("current_participants", models.IntegerField(default=0)),
                (
                    "price_per_session",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="amenities.amenity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AmenityBlockAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_assignments",
                        to="amenities.amenity",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_assignments",
                        to="properties.block",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amenity_block_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity Block Assignment",
                "verbose_name_plural": "Amenity Block Assignments",
                "ordering": ["block__building__name", "block__name"],
            },
        ),
        migrations.CreateModel(
            name="AmenityUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "people_count",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("entry_method", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("issues_reported", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="amenities.amenity",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_logs",
                        to="amenities.amenitybooking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amenity_access_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity Usage Log",
                "verbose_name_plural": "Amenity Usage Logs",
                "ordering": ["-entry_time"],
                "indexes": [
                    models.Index(
                        fields=["amenity", "entry_time"],
                        name="amenities_a_amenity_4bf5c6_idx",
                    ),
                    models.Index(
                        fields=["user"], name="amenities_a_user_id_d53e31_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AmenityReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300)),
                ("review", models.TextField()),
                (
                    "cleanliness_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "maintenance_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "staff_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("photos", models.JSONField(blank=True, default=list)),
                ("is_published", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("helpful_count", models.IntegerField(default=0)),
                ("management_response", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="amenities.amenity",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="amenities.amenitybooking",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews_moderated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity Review",
                "verbose_name_plural": "Amenity Reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["amenity", "rating"],
                        name="amenities_a_amenity_d76c51_idx",
                    ),
                    models.Index(
                        fields=["is_published"], name="amenities_a_is_publ_26e1f4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AmenityMaintenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine Maintenance"),
                            ("repair", "Repair"),
                            ("inspection", "Inspection"),
                            ("cleaning", "Deep Cleaning"),
                            ("upgrade", "Upgrade"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("scheduled_date", models.DateField()),
                ("scheduled_start", models.TimeField()),
                ("scheduled_end", models.TimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                ("vendor_contact", models.CharField(blank=True, max_length=100)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "actual_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("work_performed", models.TextField(blank=True)),
                ("parts_replaced", models.JSONField(blank=True, default=list)),
                ("issues_found", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("before_photos", models.JSONField(blank=True, default=list)),
                ("after_photos", models.JSONField(blank=True, default=list)),
                ("documents", models.JSONField(blank=True, default=list)),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                ("completion_notes", models.TextField(blank=True)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="amenities.amenity",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amenity_maintenance_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity Maintenance",
                "verbose_name_plural": "Amenity Maintenance Records",
                "ordering": ["-scheduled_date"],
                "indexes": [
                    models.Index(
                        fields=["amenity", "status"],
                        name="amenities_a_amenity_db2f81_idx",
                    ),
                    models.Index(
                        fields=["scheduled_date"], name="amenities_a_schedul_8c6ecf_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="amenitybooking",
            index=models.Index(
                fields=["booking_number"], name="amenities_a_booking_f731f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amenitybooking",
            index=models.Index(
                fields=["amenity", "booking_date"],
                name="amenities_a_amenity_71bcb3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenitybooking",
            index=models.Index(
                fields=["booked_by", "status"], name="amenities_a_booked__297548_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amenitybooking",
            index=models.Index(fields=["status"], name="amenities_a_status_c8168c_idx"),
        ),
        migrations.AddIndex(
            model_name="amenityblockassignment",
            index=models.Index(
                fields=["amenity", "block"], name="amenities_a_amenity_b61b25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amenityblockassignment",
            index=models.Index(fields=["block"], name="amenities_a_block_i_51b8a0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="amenityblockassignment",
            unique_together={("amenity", "block")},
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["amenity_type", "status"], name="amenities_a_amenity_e8209d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["is_bookable"], name="amenities_a_is_book_6c1200_idx"
            ),
        ),
    ]
