# Generated by Django 4.2.11 on 2026-05-17 09:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visitor_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("id_type", models.CharField(blank=True, max_length=50)),
                ("id_number", models.CharField(blank=True, max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="visitors/photos/%Y/%m/"
                    ),
                ),
                ("vehicle_make", models.CharField(blank=True, max_length=100)),
                ("vehicle_model", models.CharField(blank=True, max_length=100)),
                ("vehicle_color", models.CharField(blank=True, max_length=50)),
                ("vehicle_plate", models.CharField(blank=True, max_length=20)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("is_blacklisted", models.BooleanField(default=False)),
                ("blacklist_reason", models.TextField(blank=True)),
                ("blacklisted_at", models.DateTimeField(blank=True, null=True)),
                ("first_visit", models.DateTimeField(auto_now_add=True)),
                ("last_visit", models.DateTimeField(auto_now=True)),
                ("visit_count", models.IntegerField(default=0)),
                (
                    "blacklisted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blacklisted_visitors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_visit"],
            },
        ),
        migrations.CreateModel(
            name="VisitorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("requires_approval", models.BooleanField(default=True)),
                (
                    "max_duration_hours",
                    models.IntegerField(
                        default=24, help_text="Maximum visit duration in hours"
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#007bff", help_text="Hex color for UI", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VisitorPass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pass_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("purpose", models.TextField()),
                ("building", models.CharField(max_length=100)),
                ("unit_number", models.CharField(max_length=20)),
                ("expected_arrival", models.DateTimeField()),
                ("expected_departure", models.DateTimeField()),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                ("actual_departure", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="visitors/qr_codes/"
                    ),
                ),
                (
                    "access_code",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("security_notes", models.TextField(blank=True)),
                ("can_drive_in", models.BooleanField(default=False)),
                ("requires_escort", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passes",
                        to="visitors.visitor",
                    ),
                ),
                (
                    "visitor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="visitors.visitortype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("check_in", "Check In"),
                            ("check_out", "Check Out"),
                            ("denied_entry", "Denied Entry"),
                            ("alert", "Security Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gate_number", models.CharField(blank=True, max_length=50)),
                ("entry_point", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("health_screening_passed", models.BooleanField(default=True)),
                (
                    "entry_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="visitors/entry_photos/%Y/%m/"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "security_staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visitor_pass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="visitors.visitorpass",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="VisitorFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Very Poor"),
                            (2, "2 - Poor"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ]
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "security_staff_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Very Poor"),
                            (2, "2 - Poor"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "process_ease_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Very Poor"),
                            (2, "2 - Poor"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        null=True,
                    ),
                ),
                ("would_recommend", models.BooleanField(default=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visitor_pass",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="visitors.visitorpass",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="BlacklistedVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                ("is_permanent", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "blacklisted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blacklist_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visitor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_record",
                        to="visitors.visitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-blacklisted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="visitorpass",
            index=models.Index(
                fields=["status", "-created_at"], name="visitors_vi_status_663263_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorpass",
            index=models.Index(
                fields=["expected_arrival"], name="visitors_vi_expecte_f1ccca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorpass",
            index=models.Index(fields=["host"], name="visitors_vi_host_id_0ec7ad_idx"),
        ),
        migrations.AddIndex(
            model_name="visitorpass",
            index=models.Index(
                fields=["host", "status"], name="visitors_vi_host_id_c72efc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorpass",
            index=models.Index(
                fields=["visitor", "created_at"], name="visitors_vi_visitor_f5828f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorpass",
            index=models.Index(
                fields=["status", "expected_arrival"],
                name="visitors_vi_status_c3665c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visitorlog",
            index=models.Index(
                fields=["-timestamp"], name="visitors_vi_timesta_aa909a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorlog",
            index=models.Index(
                fields=["log_type"], name="visitors_vi_log_typ_dc734e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(fields=["phone"], name="visitors_vi_phone_3827a1_idx"),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(fields=["email"], name="visitors_vi_email_e17823_idx"),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(
                fields=["-last_visit"], name="visitors_vi_last_vi_ff9376_idx"
            ),
        ),
    ]
