# Generated by Django 4.2.11 on 2026-05-17 09:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("plumbing", "Plumbing"),
                            ("electrical", "Electrical"),
                            ("hvac", "HVAC"),
                            ("pest_control", "Pest Control"),
                            ("cleaning", "Cleaning"),
                            ("landscaping", "Landscaping"),
                            ("security", "Security"),
                            ("elevator", "Elevator Maintenance"),
                            ("general", "General Maintenance"),
                        ],
                        max_length=50,
                    ),
                ),
                ("contact_person", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("insurance_number", models.CharField(blank=True, max_length=100)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total_jobs", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("plumbing", "Plumbing"),
                            ("electrical", "Electrical"),
                            ("hvac", "HVAC"),
                            ("appliance", "Appliance"),
                            ("carpentry", "Carpentry"),
                            ("painting", "Painting"),
                            ("flooring", "Flooring"),
                            ("pest_control", "Pest Control"),
                            ("cleaning", "Cleaning"),
                            ("security", "Security System"),
                            ("elevator", "Elevator"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-annual"),
                            ("annual", "Annual"),
                        ],
                        max_length=50,
                    ),
                ),
                ("building", models.CharField(blank=True, max_length=200)),
                ("area", models.CharField(max_length=300)),
                ("next_due_date", models.DateField()),
                ("last_completed", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("checklist_items", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_due_date"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_number", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("plumbing", "Plumbing"),
                            ("electrical", "Electrical"),
                            ("hvac", "HVAC"),
                            ("appliance", "Appliance"),
                            ("carpentry", "Carpentry"),
                            ("painting", "Painting"),
                            ("flooring", "Flooring"),
                            ("pest_control", "Pest Control"),
                            ("cleaning", "Cleaning"),
                            ("security", "Security System"),
                            ("elevator", "Elevator"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("building", models.CharField(max_length=200)),
                ("unit_number", models.CharField(max_length=50)),
                ("specific_location", models.CharField(blank=True, max_length=300)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "owner_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("requested_date", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_date", models.DateTimeField(blank=True, null=True)),
                ("assigned_date", models.DateTimeField(blank=True, null=True)),
                ("started_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("preferred_time", models.TimeField(blank=True, null=True)),
                ("access_instructions", models.TextField(blank=True)),
                ("is_occupied", models.BooleanField(default=True)),
                ("work_performed", models.TextField(blank=True)),
                ("parts_used", models.JSONField(blank=True, default=list)),
                (
                    "parts_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "labor_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("photos_before", models.JSONField(blank=True, default=list)),
                ("photos_after", models.JSONField(blank=True, default=list)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("feedback_date", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("technician_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_requests",
                        to="properties.lease",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_maintenance_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_maintenance_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_requests",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["request_number"], name="maintenance_request_e2a50e_idx"
                    ),
                    models.Index(
                        fields=["status", "priority"],
                        name="maintenance_status_b5e015_idx",
                    ),
                    models.Index(
                        fields=["category"], name="maintenance_categor_bc6b70_idx"
                    ),
                    models.Index(
                        fields=["requested_by", "created_at"],
                        name="maintenance_request_fdb574_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="maintenance_assigne_70195a_idx",
                    ),
                ],
            },
        ),
    ]
