# Generated by Django 4.2.11 on 2026-06-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_maintenancerequest_request_type"),
    ]

    operations = []
