# Generated by Django 4.2.11 on 2026-05-17 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Area / Zone",
                "verbose_name_plural": "Areas / Zones",
                "ordering": ["city_ref__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Block identifier e.g. A, B, North Wing",
                        max_length=100,
                    ),
                ),
                (
                    "building_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("mixed", "Mixed Use"),
                            ("apartment", "Apartment"),
                        ],
                        default="residential",
                        max_length=50,
                    ),
                ),
                ("year_built", models.IntegerField(blank=True, null=True)),
                ("total_floors", models.IntegerField(default=0)),
                (
                    "apartments_per_floor",
                    models.IntegerField(
                        default=0, help_text="Number of apartments on each floor"
                    ),
                ),
                ("total_units", models.IntegerField(default=0)),
                (
                    "property_area",
                    models.FloatField(
                        blank=True, help_text="Total property area in sq ft", null=True
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Business name (for commercial/mixed wings)",
                        max_length=255,
                    ),
                ),
                (
                    "business_registration_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Business registration / GST number",
                        max_length=100,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line3",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("landmark", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Soft delete / activation flag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Block",
                "verbose_name_plural": "Blocks",
                "ordering": ["building", "name"],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line3",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("landmark", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(default="", max_length=100)),
                ("district", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(default="", max_length=100)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "blocks",
                    models.JSONField(
                        blank=True, default=list, help_text="List of block names"
                    ),
                ),
                (
                    "num_blocks",
                    models.IntegerField(
                        default=0, help_text="Number of blocks in this building"
                    ),
                ),
                ("total_floors", models.IntegerField(blank=True, null=True)),
                (
                    "apartments_per_floor",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Number of apartments on each floor (legacy/fallback)",
                        null=True,
                    ),
                ),
                ("total_units", models.IntegerField(blank=True, null=True)),
                (
                    "building_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("mixed", "Mixed Use"),
                            ("apartment", "Apartment"),
                        ],
                        default="residential",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("year_built", models.IntegerField(blank=True, null=True)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Soft delete / activation flag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "managed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_buildings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("floor_number", models.IntegerField()),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional label e.g. Ground, Mezzanine",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Soft delete / activation flag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="properties.block",
                    ),
                ),
            ],
            options={
                "verbose_name": "Floor",
                "verbose_name_plural": "Floors",
                "ordering": ["block", "floor_number"],
            },
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "maintenance_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "late_fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("late_fee_applicable_date", models.DateField(blank=True, null=True)),
                ("agreement_signed", models.BooleanField(default=False)),
                ("agreement_signed_date", models.DateField(blank=True, null=True)),
                (
                    "agreement_document",
                    models.FileField(
                        blank=True, null=True, upload_to="lease_agreements/"
                    ),
                ),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_leases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PropertyCity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("state", models.CharField(default="", max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
                "unique_together": {("name", "state")},
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("unit_number", models.CharField(max_length=50)),
                ("block", models.CharField(blank=True, max_length=50, null=True)),
                ("floor", models.IntegerField(blank=True, null=True)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("owner_occupied", "Owner Occupied"),
                            ("tenant_occupied", "Tenant Occupied"),
                            ("vacant", "Vacant"),
                        ],
                        default="vacant",
                        max_length=20,
                    ),
                ),
                (
                    "unit_category",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                        ],
                        default="residential",
                        help_text="Category for mixed-use wings",
                        max_length=20,
                    ),
                ),
                (
                    "property_area",
                    models.FloatField(
                        blank=True,
                        help_text="Unit area in sq ft (auto-filled from wing)",
                        null=True,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Business name (required for commercial units)",
                        max_length=255,
                    ),
                ),
                (
                    "business_registration_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Business registration / GST number",
                        max_length=100,
                    ),
                ),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                (
                    "bathrooms",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("square_feet", models.IntegerField(blank=True, null=True)),
                (
                    "maintenance_rate_rupees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("maintenance_rate_sqfeet", models.IntegerField(blank=True, null=True)),
                (
                    "monthly_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "monthly_maintenance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "association_dues",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("INR", "INR")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "owner_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "owner_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "owner_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("owner_phone", models.CharField(blank=True, max_length=30, null=True)),
                ("owner_address", models.TextField(blank=True, null=True)),
                (
                    "current_resident",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gst_applicable", models.BooleanField(default=False)),
                (
                    "gst_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("maintenance", "Maintenance"),
                            ("reserved", "Reserved"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_occupied", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Soft delete / activation flag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="properties.building",
                    ),
                ),
                (
                    "floor_ref",
                    models.ForeignKey(
                        blank=True,
                        help_text="Links this unit to a hierarchical Floor record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apartments",
                        to="properties.floor",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["building", "floor", "unit_number"],
            },
        ),
        migrations.CreateModel(
            name="Township",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line3",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("landmark", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(default="", max_length=100)),
                ("district", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(default="", max_length=100)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("country", models.CharField(default="India", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Soft delete / activation flag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="townships",
                        to="properties.areazone",
                    ),
                ),
                (
                    "city_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="townships",
                        to="properties.propertycity",
                    ),
                ),
                (
                    "managed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_townships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Township",
                "verbose_name_plural": "Townships",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PropertyDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("lease_agreement", "Lease Agreement"),
                            ("property_deed", "Property Deed"),
                            ("insurance", "Insurance"),
                            ("tax_document", "Tax Document"),
                            ("utility_bill", "Utility Bill"),
                            ("maintenance_record", "Maintenance Record"),
                            ("inspection_report", "Inspection Report"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="property_documents/")),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.building",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.lease",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.unit",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="lease",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leases",
                to="properties.unit",
            ),
        ),
        migrations.CreateModel(
            name="FacilityManagerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("township", "Township / Colony"),
                            ("building", "Building"),
                            ("block", "Block / Sector"),
                        ],
                        max_length=10,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fm_assignments_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fm_assignments",
                        to="properties.block",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fm_assignments",
                        to="properties.building",
                    ),
                ),
                (
                    "facility_manager",
                    models.ForeignKey(
                        limit_choices_to={"role": "facility_manager"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fm_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "township",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fm_assignments",
                        to="properties.township",
                    ),
                ),
            ],
            options={
                "verbose_name": "FM Assignment",
                "verbose_name_plural": "FM Assignments",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.AddField(
            model_name="building",
            name="township",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buildings",
                to="properties.township",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block_set",
                to="properties.building",
            ),
        ),
        migrations.AddField(
            model_name="areazone",
            name="city_ref",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area_zones",
                to="properties.propertycity",
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["building", "unit_number"],
                name="properties__buildin_f959a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["status"], name="properties__status_e4b367_idx"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["unit_type"], name="properties__unit_ty_add9bf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("building", "unit_number")},
        ),
        migrations.AddIndex(
            model_name="propertydocument",
            index=models.Index(
                fields=["document_type", "uploaded_at"],
                name="properties__documen_c6127c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["status", "end_date"], name="properties__status_3e4827_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["tenant", "status"], name="properties__tenant__64cf47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["unit", "status"], name="properties__unit_id_d57644_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="floor",
            unique_together={("block", "floor_number")},
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(fields=["name"], name="properties__name_04247c_idx"),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["city", "state"], name="properties__city_cdcebd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["created_at"], name="properties__created_a598d0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="block",
            unique_together={("building", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="areazone",
            unique_together={("city_ref", "name")},
        ),
    ]
