# Generated by Django 4.2.11 on 2026-05-18 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitymanagerassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fm_assignments_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
