# Generated by Django 4.2.11 on 2026-05-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_alter_building_managed_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD")], default="USD", max_length=3
            ),
        ),
    ]
