# Generated by Django 4.2.11 on 2026-06-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_alter_unit_currency"),
    ]

    operations = []
