# Generated by Django 4.2.11 on 2026-06-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_merge_20260615_2358"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="management_fee_override_type",
            field=models.CharField(
                choices=[
                    ("none", "Use Global Default"),
                    ("percentage", "Percentage"),
                    ("fixed", "Fixed Amount"),
                ],
                default="none",
                help_text="Override the global management fee for this unit",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="management_fee_override_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override value if type is percentage or fixed",
                max_digits=10,
                null=True,
            ),
        ),
    ]
