# Generated by Django 4.2.11 on 2026-05-17 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_schema", models.CharField(db_index=True, max_length=100)),
                ("date", models.DateField(db_index=True)),
                ("metric_key", models.CharField(max_length=100)),
                ("metric_value", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Daily Metric Snapshot",
                "verbose_name_plural": "Daily Metric Snapshots",
                "ordering": ["-date", "tenant_schema", "metric_key"],
                "unique_together": {("tenant_schema", "date", "metric_key")},
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("user_logged_in", "User Logged In"),
                            ("user_logged_out", "User Logged Out"),
                            ("user_login_failed", "User Login Failed"),
                            ("user_registered", "User Registered"),
                            ("user_profile_updated", "User Profile Updated"),
                            ("password_changed", "Password Changed"),
                            ("2fa_enabled", "2FA Enabled"),
                            ("invoice_created", "Invoice Created"),
                            ("invoice_paid", "Invoice Paid"),
                            ("invoice_overdue", "Invoice Overdue"),
                            ("invoice_failed", "Invoice Failed"),
                            ("payment_plan_created", "Payment Plan Created"),
                            ("autopay_enabled", "AutoPay Enabled"),
                            ("autopay_disabled", "AutoPay Disabled"),
                            ("subscription_created", "Subscription Created"),
                            ("subscription_upgraded", "Subscription Upgraded"),
                            ("subscription_cancelled", "Subscription Cancelled"),
                            (
                                "maintenance_request_created",
                                "Maintenance Request Created",
                            ),
                            ("maintenance_assigned", "Maintenance Assigned"),
                            (
                                "maintenance_status_changed",
                                "Maintenance Status Changed",
                            ),
                            ("maintenance_resolved", "Maintenance Resolved"),
                            ("maintenance_rated", "Maintenance Rated"),
                            ("amenity_booked", "Amenity Booked"),
                            ("amenity_booking_cancelled", "Amenity Booking Cancelled"),
                            ("amenity_booking_approved", "Amenity Booking Approved"),
                            ("amenity_reviewed", "Amenity Reviewed"),
                            ("message_sent", "Message Sent"),
                            ("announcement_published", "Announcement Published"),
                            ("announcement_viewed", "Announcement Viewed"),
                            ("email_campaign_sent", "Email Campaign Sent"),
                            ("email_opened", "Email Opened"),
                            ("email_clicked", "Email Clicked"),
                            ("sms_sent", "SMS Sent"),
                            ("sms_delivered", "SMS Delivered"),
                            ("sms_failed", "SMS Failed"),
                            ("ticket_created", "Ticket Created"),
                            ("ticket_assigned", "Ticket Assigned"),
                            ("ticket_status_changed", "Ticket Status Changed"),
                            ("ticket_resolved", "Ticket Resolved"),
                            ("ticket_rated", "Ticket Rated"),
                            ("visitor_preregistered", "Visitor Pre-Registered"),
                            ("visitor_checked_in", "Visitor Checked In"),
                            ("visitor_checked_out", "Visitor Checked Out"),
                            ("document_uploaded", "Document Uploaded"),
                            ("document_downloaded", "Document Downloaded"),
                            ("document_deleted", "Document Deleted"),
                            ("incident_reported", "Incident Reported"),
                            ("access_denied", "Access Denied"),
                            ("emergency_alert_sent", "Emergency Alert Sent"),
                            ("accounting_sync_completed", "Accounting Sync Completed"),
                            ("accounting_sync_failed", "Accounting Sync Failed"),
                            ("reconciliation_started", "Reconciliation Started"),
                            ("reconciliation_completed", "Reconciliation Completed"),
                            ("app_session_started", "App Session Started"),
                            ("app_session_ended", "App Session Ended"),
                            (
                                "push_notification_received",
                                "Push Notification Received",
                            ),
                            ("push_notification_tapped", "Push Notification Tapped"),
                        ],
                        db_index=True,
                        max_length=60,
                    ),
                ),
                ("tenant_schema", models.CharField(db_index=True, max_length=100)),
                (
                    "object_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("object_id", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("web", "Web Browser"),
                            ("ios", "iOS App"),
                            ("android", "Android App"),
                            ("api", "API Client"),
                            ("other", "Other"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "session_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Event",
                "verbose_name_plural": "Analytics Events",
                "ordering": ["-created_at"],
            },
        ),
    ]
