# Generated by Django 4.2.11 on 2026-05-17 09:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("suv", "SUV"),
                            ("motorcycle", "Motorcycle"),
                            ("scooter", "Scooter"),
                            ("bicycle", "Bicycle"),
                            ("electric", "Electric Vehicle"),
                        ],
                        max_length=50,
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                (
                    "year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1900)]
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("license_plate", models.CharField(max_length=50, unique=True)),
                ("registration_number", models.CharField(max_length=100)),
                ("registration_expiry", models.DateField(blank=True, null=True)),
                ("insurance_number", models.CharField(blank=True, max_length=100)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("registration_document", models.CharField(blank=True, max_length=500)),
                ("insurance_document", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParkingSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slot_number", models.CharField(max_length=50, unique=True)),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("bike", "Motorcycle/Bike"),
                            ("visitor", "Visitor"),
                            ("disabled", "Disabled"),
                            ("electric", "Electric Vehicle"),
                            ("vip", "VIP"),
                        ],
                        max_length=50,
                    ),
                ),
                ("building", models.CharField(blank=True, max_length=200)),
                ("floor", models.CharField(max_length=50)),
                ("section", models.CharField(blank=True, max_length=50)),
                ("location_details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("reserved", "Reserved"),
                            ("maintenance", "Under Maintenance"),
                            ("disabled", "Disabled"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("has_ev_charger", models.BooleanField(default=False)),
                ("is_covered", models.BooleanField(default=False)),
                ("has_camera", models.BooleanField(default=False)),
                (
                    "monthly_rent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parking_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_slot",
                        to="parking.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["floor", "slot_number"],
            },
        ),
        migrations.CreateModel(
            name="ParkingPass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pass_number", models.CharField(max_length=50, unique=True)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("qr_code", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parking_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parking.parkingslot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passes",
                        to="parking.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParkingEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entry_time", models.DateTimeField(auto_now_add=True)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("entry_gate", models.CharField(max_length=100)),
                ("exit_gate", models.CharField(blank=True, max_length=100)),
                ("is_authorized", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parking_pass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parking.parkingpass",
                    ),
                ),
                (
                    "parking_slot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parking.parkingslot",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_entries",
                        to="parking.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_time"],
            },
        ),
        migrations.AddIndex(
            model_name="parkingslot",
            index=models.Index(
                fields=["slot_number"], name="parking_par_slot_nu_910564_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parkingslot",
            index=models.Index(
                fields=["status", "slot_type"], name="parking_par_status_b0214e_idx"
            ),
        ),
    ]
