# Generated by Django 4.2.11 on 2026-05-17 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservableResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("facility", "Facility"),
                            ("room", "Meeting Room"),
                            ("equipment", "Equipment"),
                            ("space", "Common Space"),
                            ("vehicle", "Vehicle"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("capacity", models.IntegerField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="reservations/resources/"),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("available_from", models.TimeField(default="06:00")),
                ("available_until", models.TimeField(default="22:00")),
                (
                    "available_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of weekday numbers (0=Mon, 6=Sun). Empty = every day.",
                    ),
                ),
                (
                    "max_duration_hours",
                    models.DecimalField(decimal_places=1, default=4.0, max_digits=5),
                ),
                ("min_advance_hours", models.IntegerField(default=1)),
                ("max_advance_days", models.IntegerField(default=30)),
                ("is_free", models.BooleanField(default=True)),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("requires_approval", models.BooleanField(default=False)),
                ("rules", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["resource_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reservation_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("guest_count", models.IntegerField(default=1)),
                ("guest_names", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("checked_in", "Checked In"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("purpose", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("deposit_paid", models.BooleanField(default=False)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reserved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservations.reservableresource",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["resource", "start_time", "end_time"],
                        name="reservation_resourc_71be40_idx",
                    ),
                    models.Index(
                        fields=["reserved_by", "-created_at"],
                        name="reservation_reserve_594a4c_idx",
                    ),
                    models.Index(
                        fields=["status", "-start_time"],
                        name="reservation_status_66ed18_idx",
                    ),
                ],
            },
        ),
    ]
