# Generated by Django 4.2.11 on 2026-05-17 09:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("temporary", "Temporary"),
                            ("recurring", "Recurring"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("access_areas", models.JSONField(default=list)),
                (
                    "access_level",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("card_number", models.CharField(max_length=100, unique=True)),
                ("card_type", models.CharField(max_length=50)),
                ("pin_code", models.CharField(blank=True, max_length=20)),
                ("biometric_registered", models.BooleanField(default=False)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("time_restrictions", models.JSONField(blank=True, default=dict)),
                ("day_restrictions", models.JSONField(blank=True, default=list)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("revoke_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_cards_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_cards_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Control",
                "verbose_name_plural": "Access Controls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityGuard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (6 AM - 2 PM)"),
                            ("afternoon", "Afternoon (2 PM - 10 PM)"),
                            ("night", "Night (10 PM - 6 AM)"),
                            ("rotating", "Rotating Shifts"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("emergency_contact_name", models.CharField(max_length=200)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                ("joining_date", models.DateField()),
                ("last_working_date", models.DateField(blank=True, null=True)),
                ("license_number", models.CharField(max_length=100)),
                ("license_expiry", models.DateField()),
                ("training_completed", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("assigned_building", models.CharField(blank=True, max_length=200)),
                ("assigned_gate", models.CharField(blank=True, max_length=50)),
                ("assigned_area", models.CharField(blank=True, max_length=200)),
                ("incidents_reported", models.IntegerField(default=0)),
                ("incidents_resolved", models.IntegerField(default=0)),
                (
                    "performance_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_guards_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Guard",
                "verbose_name_plural": "Security Guards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("incident_number", models.CharField(max_length=50, unique=True)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("theft", "Theft"),
                            ("vandalism", "Vandalism"),
                            ("trespassing", "Trespassing"),
                            ("fight", "Fight/Altercation"),
                            ("fire", "Fire Incident"),
                            ("medical", "Medical Emergency"),
                            ("suspicious", "Suspicious Activity"),
                            ("noise", "Noise Complaint"),
                            ("parking", "Parking Violation"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=300)),
                ("building", models.CharField(blank=True, max_length=200)),
                ("unit_number", models.CharField(blank=True, max_length=50)),
                ("occurred_at", models.DateTimeField()),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("suspects", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("investigating", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                            ("closed", "Closed"),
                        ],
                        default="reported",
                        max_length=20,
                    ),
                ),
                ("investigation_notes", models.TextField(blank=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("action_taken", models.TextField(blank=True)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("videos", models.JSONField(blank=True, default=list)),
                ("documents", models.JSONField(blank=True, default=list)),
                ("police_notified", models.BooleanField(default=False)),
                ("police_report_number", models.CharField(blank=True, max_length=100)),
                ("management_notified", models.BooleanField(default=False)),
                ("insurance_claim_filed", models.BooleanField(default=False)),
                (
                    "insurance_claim_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("property_damage", models.BooleanField(default=False)),
                (
                    "estimated_damage_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("items_stolen", models.JSONField(blank=True, default=list)),
                (
                    "estimated_loss_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("requires_followup", models.BooleanField(default=False)),
                ("followup_date", models.DateField(blank=True, null=True)),
                ("followup_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_incidents",
                        to="security.securityguard",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "witnesses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="witnessed_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Incident",
                "verbose_name_plural": "Security Incidents",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAnnouncement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("target_buildings", models.JSONField(blank=True, default=list)),
                ("target_units", models.JSONField(blank=True, default=list)),
                ("send_to_all", models.BooleanField(default=False)),
                ("send_email", models.BooleanField(default=True)),
                ("send_sms", models.BooleanField(default=False)),
                ("send_push", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("sent_count", models.IntegerField(default=0)),
                ("read_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_announcements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Announcement",
                "verbose_name_plural": "Security Announcements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatrolLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("patrol_route", models.CharField(max_length=200)),
                ("checkpoints", models.JSONField(default=list)),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                            ("incident_found", "Incident Found"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("checkpoints_completed", models.JSONField(default=list)),
                ("checkpoints_skipped", models.JSONField(default=list)),
                ("observations", models.TextField(blank=True)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("weather_conditions", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patrols",
                        to="security.securityguard",
                    ),
                ),
                (
                    "incidents_found",
                    models.ManyToManyField(
                        blank=True,
                        related_name="found_during_patrols",
                        to="security.securityincident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patrol Log",
                "verbose_name_plural": "Patrol Logs",
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("sos", "SOS"),
                            ("fire", "Fire"),
                            ("medical", "Medical Emergency"),
                            ("security_threat", "Security Threat"),
                            ("natural_disaster", "Natural Disaster"),
                            ("evacuation", "Evacuation"),
                            ("lockdown", "Lockdown"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("responding", "Responding"),
                            ("resolved", "Resolved"),
                            ("false_alarm", "False Alarm"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=300)),
                ("building", models.CharField(blank=True, max_length=200)),
                ("unit_number", models.CharField(blank=True, max_length=50)),
                ("coordinates", models.JSONField(blank=True, default=dict)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("response_notes", models.TextField(blank=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("police_called", models.BooleanField(default=False)),
                ("fire_dept_called", models.BooleanField(default=False)),
                ("ambulance_called", models.BooleanField(default=False)),
                ("external_response_time", models.DurationField(blank=True, null=True)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("videos", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts_acknowledged",
                        to="security.securityguard",
                    ),
                ),
                (
                    "responders",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alerts_responded",
                        to="security.securityguard",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_alerts_triggered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Alert",
                "verbose_name_plural": "Emergency Alerts",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="CCTVCamera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("camera_id", models.CharField(max_length=100, unique=True)),
                ("camera_name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=300)),
                ("building", models.CharField(blank=True, max_length=200)),
                ("floor", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("mac_address", models.CharField(blank=True, max_length=100)),
                ("camera_type", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(max_length=100)),
                ("model_number", models.CharField(max_length=100)),
                ("installed_date", models.DateField()),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("next_maintenance", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Under Maintenance"),
                            ("faulty", "Faulty"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("is_recording", models.BooleanField(default=True)),
                ("has_audio", models.BooleanField(default=False)),
                ("has_night_vision", models.BooleanField(default=True)),
                ("has_motion_detection", models.BooleanField(default=True)),
                ("pan_tilt_zoom", models.BooleanField(default=False)),
                ("recording_quality", models.CharField(blank=True, max_length=50)),
                ("storage_days", models.IntegerField(default=30)),
                ("stream_url", models.CharField(blank=True, max_length=500)),
                ("coverage_area", models.TextField(blank=True)),
                ("viewing_angle", models.IntegerField(blank=True, null=True)),
                ("last_online", models.DateTimeField(blank=True, null=True)),
                (
                    "uptime_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CCTV Camera",
                "verbose_name_plural": "CCTV Cameras",
                "ordering": ["building", "location"],
                "indexes": [
                    models.Index(
                        fields=["camera_id"], name="security_cc_camera__02e45d_idx"
                    ),
                    models.Index(
                        fields=["status"], name="security_cc_status_f5939e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("access_point", models.CharField(max_length=200)),
                ("access_area", models.CharField(max_length=200)),
                ("card_number", models.CharField(max_length=100)),
                (
                    "access_result",
                    models.CharField(
                        choices=[
                            ("granted", "Access Granted"),
                            ("denied", "Access Denied"),
                            ("expired", "Card Expired"),
                            ("invalid", "Invalid Card"),
                            ("restricted_time", "Restricted Time"),
                            ("restricted_area", "Restricted Area"),
                        ],
                        max_length=50,
                    ),
                ),
                ("access_method", models.CharField(max_length=50)),
                ("denial_reason", models.TextField(blank=True)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("is_suspicious", models.BooleanField(default=False)),
                ("photo_captured", models.CharField(blank=True, max_length=500)),
                (
                    "access_control",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="security.accesscontrol",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Log",
                "verbose_name_plural": "Access Logs",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visitor_name", models.CharField(max_length=200)),
                ("visitor_phone", models.CharField(max_length=20)),
                ("visitor_email", models.EmailField(blank=True, max_length=254)),
                (
                    "visitor_type",
                    models.CharField(
                        choices=[
                            ("guest", "Guest"),
                            ("delivery", "Delivery"),
                            ("service", "Service Provider"),
                            ("contractor", "Contractor"),
                            ("vendor", "Vendor"),
                            ("real_estate", "Real Estate Agent"),
                            ("government", "Government Official"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("visitor_company", models.CharField(blank=True, max_length=200)),
                (
                    "number_of_visitors",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("id_type", models.CharField(blank=True, max_length=50)),
                ("id_number", models.CharField(blank=True, max_length=100)),
                ("id_photo", models.CharField(blank=True, max_length=500)),
                ("visitor_photo", models.CharField(blank=True, max_length=500)),
                ("vehicle_number", models.CharField(blank=True, max_length=50)),
                ("vehicle_type", models.CharField(blank=True, max_length=100)),
                ("vehicle_make", models.CharField(blank=True, max_length=100)),
                ("vehicle_color", models.CharField(blank=True, max_length=50)),
                ("host_unit", models.CharField(max_length=50)),
                ("host_building", models.CharField(max_length=200)),
                ("purpose", models.TextField()),
                ("is_pre_approved", models.BooleanField(default=False)),
                ("approval_code", models.CharField(blank=True, max_length=20)),
                ("expected_arrival", models.DateTimeField()),
                ("expected_departure", models.DateTimeField(blank=True, null=True)),
                ("actual_checkin", models.DateTimeField(blank=True, null=True)),
                ("actual_checkout", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("denial_reason", models.TextField(blank=True)),
                ("items_carried", models.TextField(blank=True)),
                ("special_instructions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "temperature_recorded",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("access_card_issued", models.BooleanField(default=False)),
                ("access_card_number", models.CharField(blank=True, max_length=50)),
                ("access_card_returned", models.BooleanField(default=False)),
                ("host_notified", models.BooleanField(default=False)),
                (
                    "host_notification_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_in_visitors",
                        to="security.securityguard",
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_out_visitors",
                        to="security.securityguard",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_visitors_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pre_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pre_approved_visitors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitor Log",
                "verbose_name_plural": "Visitor Logs",
                "ordering": ["-expected_arrival"],
                "indexes": [
                    models.Index(
                        fields=["visitor_phone"], name="security_vi_visitor_ff9935_idx"
                    ),
                    models.Index(
                        fields=["host", "status"], name="security_vi_host_id_1e774a_idx"
                    ),
                    models.Index(
                        fields=["-expected_arrival"],
                        name="security_vi_expecte_0ff396_idx",
                    ),
                    models.Index(
                        fields=["status"], name="security_vi_status_5f7c96_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["incident_number"], name="security_se_inciden_d070b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["incident_type", "status"],
                name="security_se_inciden_0cde7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["severity"], name="security_se_severit_2cdee4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["-occurred_at"], name="security_se_occurre_2cda46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityguard",
            index=models.Index(
                fields=["employee_id"], name="security_se_employe_d20350_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityguard",
            index=models.Index(
                fields=["status", "shift"], name="security_se_status_8517af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patrollog",
            index=models.Index(
                fields=["guard", "status"], name="security_pa_guard_i_74d16b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patrollog",
            index=models.Index(
                fields=["-scheduled_start"], name="security_pa_schedul_ce0a96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(
                fields=["status", "priority"], name="security_em_status_b8be7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(
                fields=["-triggered_at"], name="security_em_trigger_ae858c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["-attempted_at"], name="security_ac_attempt_0f03d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["access_result"], name="security_ac_access__8f090d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["is_suspicious"], name="security_ac_is_susp_4bcde2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesscontrol",
            index=models.Index(
                fields=["card_number"], name="security_ac_card_nu_f29d88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesscontrol",
            index=models.Index(
                fields=["user", "status"], name="security_ac_user_id_12c2a8_idx"
            ),
        ),
    ]
