# Generated by Django 4.2.11 on 2026-05-17 09:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoPayEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enrollment_number", models.CharField(max_length=50, unique=True)),
                ("enrollment_type", models.CharField(default="rent", max_length=50)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "mandate_limit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "razorpay_customer_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "razorpay_subscription_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "razorpay_plan_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("start_date", models.DateField()),
                ("next_payment_date", models.DateField()),
                ("last_payment_date", models.DateField(blank=True, null=True)),
                (
                    "billing_day",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Authorization"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("max_retry_attempts", models.IntegerField(default=3)),
                ("current_retry_count", models.IntegerField(default=0)),
                ("retry_interval_days", models.IntegerField(default=3)),
                ("total_payments", models.IntegerField(default=0)),
                ("successful_payments", models.IntegerField(default=0)),
                ("failed_payments", models.IntegerField(default=0)),
                (
                    "total_amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("notify_before_days", models.IntegerField(default=3)),
                ("send_payment_confirmation", models.BooleanField(default=True)),
                ("send_failure_notification", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("paused_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autopay_enrollments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("rent", "Rent"),
                            ("maintenance_fee", "Maintenance Fee"),
                            ("parking_fee", "Parking Fee"),
                            ("amenity_fee", "Amenity Fee"),
                            ("security_deposit", "Security Deposit"),
                            ("late_fee", "Late Fee"),
                            ("utility", "Utility Bill"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("building", models.CharField(max_length=200)),
                ("unit_number", models.CharField(max_length=50)),
                (
                    "owner_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "payment_responsibility",
                    models.CharField(
                        choices=[("tenant", "Tenant"), ("owner", "Owner")],
                        default="tenant",
                        max_length=20,
                    ),
                ),
                (
                    "transfer_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("transfer_requested_at", models.DateTimeField(blank=True, null=True)),
                ("transfer_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("transfer_rejection_reason", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "late_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("viewed", "Viewed"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("line_items", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                ("recurring_frequency", models.CharField(blank=True, max_length=20)),
                ("pdf_file", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "maintenance_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="maintenance.maintenancerequest",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_invoices",
                        to="payments.invoice",
                    ),
                ),
                (
                    "responsible_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfer_requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_transfer_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfer_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_transfer_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment_number", models.CharField(max_length=50, unique=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("razorpay_upi", "UPI (Razorpay)"),
                            ("razorpay_card", "Card (Razorpay)"),
                            ("razorpay_netbanking", "Net Banking (Razorpay)"),
                            ("razorpay_wallet", "Wallet (Razorpay)"),
                            ("stripe_card", "Card (Stripe)"),
                            ("stripe_upi", "UPI (Stripe)"),
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("bank_transfer", "Bank Transfer"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("gateway_payment_id", models.CharField(blank=True, max_length=200)),
                ("gateway_order_id", models.CharField(blank=True, max_length=200)),
                ("gateway_signature", models.CharField(blank=True, max_length=500)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "gateway_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("refund_reason", models.TextField(blank=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                ("receipt_url", models.CharField(blank=True, max_length=500)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gateway_type",
                    models.CharField(
                        choices=[
                            ("razorpay", "Razorpay"),
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("manual", "Manual/Cash"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_test_mode", models.BooleanField(default=True)),
                ("public_key", models.CharField(blank=True, max_length=500)),
                ("secret_key", models.CharField(blank=True, max_length=500)),
                ("webhook_secret", models.CharField(blank=True, max_length=500)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("total_transactions", models.IntegerField(default=0)),
                ("successful_transactions", models.IntegerField(default=0)),
                ("failed_transactions", models.IntegerField(default=0)),
                (
                    "total_amount_processed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["gateway_type"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("refund_number", models.CharField(max_length=50, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gateway_refund_id", models.CharField(blank=True, max_length=200)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_number", models.CharField(max_length=50, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment Received"),
                            ("refund", "Refund Issued"),
                            ("fee", "Fee Charged"),
                            ("adjustment", "Adjustment"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.payment",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.refund",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RazorpayWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type"], name="payments_ra_event_t_4b92f9_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="payments_ra_created_4421e8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("before_due", "Before Due Date"),
                            ("on_due", "On Due Date"),
                            ("after_due", "After Due Date (Overdue)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("send_email", models.BooleanField(default=True)),
                ("send_sms", models.BooleanField(default=False)),
                ("send_push", models.BooleanField(default=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_for", models.DateTimeField()),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="payments.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan_number", models.CharField(max_length=50, unique=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "installments",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2)]
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("start_date", models.DateField()),
                ("frequency", models.CharField(default="monthly", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("defaulted", "Defaulted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("installments_paid", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_plans",
                        to="payments.invoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("razorpay_card", "Card (Razorpay)"),
                            ("razorpay_upi", "UPI (Razorpay)"),
                            ("stripe_card", "Card (Stripe)"),
                            ("paypal", "PayPal"),
                            ("bank_account", "Bank Account"),
                        ],
                        max_length=50,
                    ),
                ),
                ("gateway_payment_method_id", models.CharField(max_length=200)),
                ("gateway_customer_id", models.CharField(blank=True, max_length=200)),
                ("card_last4", models.CharField(blank=True, max_length=4)),
                ("card_brand", models.CharField(blank=True, max_length=50)),
                ("card_exp_month", models.IntegerField(blank=True, null=True)),
                ("card_exp_year", models.IntegerField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=200)),
                ("account_last4", models.CharField(blank=True, max_length=4)),
                ("upi_id", models.CharField(blank=True, max_length=200)),
                ("is_default", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.paymentgateway",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.paymentgateway",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="payments.invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("installment_number", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.payment",
                    ),
                ),
                (
                    "payment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_installments",
                        to="payments.paymentplan",
                    ),
                ),
            ],
            options={
                "ordering": ["payment_plan", "installment_number"],
            },
        ),
        migrations.CreateModel(
            name="AutoPaymentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("attempted_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("attempt_number", models.IntegerField(default=1)),
                ("next_retry_date", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("user_notified", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_logs",
                        to="payments.autopayenrollment",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="autopayenrollment",
            name="gateway",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.paymentgateway",
            ),
        ),
        migrations.AddField(
            model_name="autopayenrollment",
            name="payment_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="autopayenrollment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autopay_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RecurringInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template_number", models.CharField(max_length=50, unique=True)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("rent", "Rent"),
                            ("maintenance_fee", "Maintenance Fee"),
                            ("parking_fee", "Parking Fee"),
                            ("amenity_fee", "Amenity Fee"),
                            ("security_deposit", "Security Deposit"),
                            ("late_fee", "Late Fee"),
                            ("utility", "Utility Bill"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("building", models.CharField(max_length=200)),
                ("unit_number", models.CharField(max_length=50)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("next_invoice_date", models.DateField()),
                (
                    "billing_day",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("auto_pay_enabled", models.BooleanField(default=False)),
                ("line_items_template", models.JSONField(blank=True, default=list)),
                ("invoices_generated", models.IntegerField(default=0)),
                ("last_invoice_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "autopay_enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_invoices",
                        to="payments.autopayenrollment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_invoices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["template_number"],
                        name="payments_re_templat_534c67_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="payments_re_user_id_37e2c4_idx"
                    ),
                    models.Index(
                        fields=["next_invoice_date", "status"],
                        name="payments_re_next_in_ec1560_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_number"], name="payments_pa_payment_a0847d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "status"], name="payments_pa_user_id_01767a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["gateway_transaction_id"], name="payments_pa_gateway_2a3159_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_pa_status_7ad4af_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="payments_in_invoice_3fa711_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "status"], name="payments_in_user_id_a545de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="payments_in_due_dat_9c830a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="payments_in_status_45b876_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="installment",
            unique_together={("payment_plan", "installment_number")},
        ),
        migrations.AddIndex(
            model_name="autopaymentlog",
            index=models.Index(
                fields=["enrollment", "status"], name="payments_au_enrollm_165ffb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autopaymentlog",
            index=models.Index(
                fields=["scheduled_date"], name="payments_au_schedul_705e42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autopaymentlog",
            index=models.Index(fields=["status"], name="payments_au_status_a80c3d_idx"),
        ),
        migrations.AddIndex(
            model_name="autopayenrollment",
            index=models.Index(
                fields=["enrollment_number"], name="payments_au_enrollm_b48643_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autopayenrollment",
            index=models.Index(
                fields=["user", "status"], name="payments_au_user_id_9a2452_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autopayenrollment",
            index=models.Index(
                fields=["next_payment_date", "status"],
                name="payments_au_next_pa_a47650_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="autopayenrollment",
            index=models.Index(
                fields=["razorpay_subscription_id"],
                name="payments_au_razorpa_cd93bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="autopayenrollment",
            index=models.Index(
                fields=["stripe_subscription_id"], name="payments_au_stripe__fb4d30_idx"
            ),
        ),
    ]
