# Generated by Django 4.2.11 on 2026-06-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgateway",
            name="charges_enabled",
            field=models.BooleanField(
                default=False,
                help_text="True when Stripe confirms HOA can accept payments",
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="onboarding_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("NOT_CONNECTED", "Not Connected"),
                    ("PENDING", "Pending KYC"),
                    ("ACTIVE", "Active"),
                    ("DISABLED", "Disabled"),
                ],
                default="NOT_CONNECTED",
                help_text="Stripe Connect onboarding status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="payouts_enabled",
            field=models.BooleanField(
                default=False,
                help_text="True when HOA bank account is verified for payouts",
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="stripe_connected_account_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Express Connected Account ID (acct_xxx)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="WebhookEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["stripe_event_id"],
                        name="payments_we_stripe__166479_idx",
                    )
                ],
            },
        ),
    ]
