# Generated by Django 4.2.11 on 2026-06-22 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payments.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0009_alter_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="late_fee_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="bank_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="bank_last4",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="business_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="business_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="financial_connections_account_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="onboarding_started",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="stripe_verification_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="support_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("rent", "Total Rent"),
                    ("maintenance_fee", "Total Dues"),
                    ("parking_fee", "Parking Fee"),
                    ("amenity_fee", "Amenity Fee"),
                    ("security_deposit", "Security Deposit"),
                    ("late_fee", "Late Fee"),
                    ("utility", "Utility Bill"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymentgateway",
            name="secret_key",
            field=payments.models.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="paymentgateway",
            name="webhook_secret",
            field=payments.models.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="recurringinvoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("rent", "Total Rent"),
                    ("maintenance_fee", "Total Dues"),
                    ("parking_fee", "Parking Fee"),
                    ("amenity_fee", "Amenity Fee"),
                    ("security_deposit", "Security Deposit"),
                    ("late_fee", "Late Fee"),
                    ("utility", "Utility Bill"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="OwnerPaymentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_connected_account_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Express Connected Account ID (acct_xxx) for the owner",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "charges_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="True when Stripe confirms owner can accept payments",
                    ),
                ),
                (
                    "payouts_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="True when owner bank account is verified for payouts",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("NOT_CONNECTED", "Not Connected"),
                            ("PENDING", "Pending KYC"),
                            ("ACTIVE", "Active"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="NOT_CONNECTED",
                        help_text="Stripe Connect onboarding status",
                        max_length=20,
                    ),
                ),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                ("bank_last4", models.CharField(blank=True, max_length=4, null=True)),
                ("bank_connected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        limit_choices_to={"role__in": ["owner"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
