# Generated by Django 4.2.11 on 2026-05-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataExportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requestedBy",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("dataTypes", models.JSONField(default=list)),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("json", "JSON"), ("xlsx", "Excel")],
                        default="csv",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("dateFrom", models.DateField(blank=True, null=True)),
                ("dateTo", models.DateField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, default="", max_length=500)),
                ("error_message", models.TextField(blank=True, default="")),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_export_record",
                "ordering": ["-createdAt"],
            },
        ),
    ]
