# reports/models.py
import uuid
import random
import string
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()


class ReportTemplate(models.Model):
    REPORT_TYPES = [
        ('financial', 'Financial'),
        ('occupancy', 'Occupancy'),
        ('maintenance', 'Maintenance'),
        ('payment', 'Payment Collection'),
        ('utility', 'Utility Consumption'),
        ('visitor', 'Visitor Activity'),
        ('security', 'Security Incidents'),
        ('amenity', 'Amenity Usage'),
        ('custom', 'Custom'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    report_type = models.CharField(max_length=50, choices=REPORT_TYPES)

    # Template config
    columns = models.JSONField(default=list, blank=True)
    filters = models.JSONField(default=dict, blank=True)
    default_date_range = models.CharField(max_length=50, default='last_30_days')
    chart_config = models.JSONField(default=dict, blank=True)

    is_system = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    sort_order = models.IntegerField(default=0)

    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='report_templates_created', db_constraint=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['sort_order', 'name']

    def __str__(self):
        return f"{self.name} ({self.get_report_type_display()})"


class GeneratedReport(models.Model):
    FORMAT_CHOICES = [
        ('pdf', 'PDF'),
        ('csv', 'CSV'),
        ('xlsx', 'Excel'),
        ('json', 'JSON'),
    ]
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('generating', 'Generating'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    report_number = models.CharField(max_length=30, unique=True, blank=True)
    template = models.ForeignKey(
        ReportTemplate, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='generated_reports',
    )

    # Report config
    name = models.CharField(max_length=300)
    report_type = models.CharField(max_length=50)
    output_format = models.CharField(max_length=10, choices=FORMAT_CHOICES, default='pdf')
    parameters = models.JSONField(default=dict, blank=True)

    # Date range
    date_from = models.DateField(null=True, blank=True)
    date_to = models.DateField(null=True, blank=True)

    # Status & output
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    file = models.FileField(upload_to='reports/%Y/%m/', blank=True)
    file_size = models.BigIntegerField(default=0)
    row_count = models.IntegerField(default=0)
    error_message = models.TextField(blank=True)

    # Metadata
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='generated_reports_created', db_constraint=False)
    generated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='reports_generated', blank=True, db_constraint=False)
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.name} ({self.report_number})"

    def _generate_report_number(self):
        """Generate a unique report number like RPT-20260519-A3F2."""
        date_str = timezone.now().strftime('%Y%m%d')
        suffix = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
        return f'RPT-{date_str}-{suffix}'

    def save(self, *args, **kwargs):
        if not self.report_number:
            # Keep generating until we find a unique one
            for _ in range(10):
                candidate = self._generate_report_number()
                if not GeneratedReport.objects.filter(report_number=candidate).exists():
                    self.report_number = candidate
                    break
            else:
                # Fallback to UUID fragment if all retries fail
                self.report_number = f'RPT-{str(self.id)[:12].upper()}'
        # If report_number is already set (pre-generated by the caller), skip loop entirely
        super().save(*args, **kwargs)


class ScheduledReport(models.Model):
    FREQUENCY_CHOICES = [
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('monthly', 'Monthly'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    template = models.ForeignKey(ReportTemplate, on_delete=models.CASCADE, related_name='scheduled_reports')
    name = models.CharField(max_length=200)
    
    frequency = models.CharField(max_length=20, choices=FREQUENCY_CHOICES)
    day_of_week = models.IntegerField(null=True, blank=True)  # 0-6
    day_of_month = models.IntegerField(null=True, blank=True) # 1-31
    time_of_day = models.TimeField(default='00:00')
    
    output_format = models.CharField(max_length=10, default='pdf')
    recipients = models.ManyToManyField(User, related_name='received_scheduled_reports')
    
    is_active = models.BooleanField(default=True)
    last_run_at = models.DateTimeField(null=True, blank=True)
    next_run_at = models.DateTimeField(null=True, blank=True)

    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, db_constraint=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Schedule: {self.name} ({self.frequency})"
